### ISSUE TITLE
Add contact page

### ISSUE THREAD

**Issue by kymppi** [kymppi/new.midka.dev#4]
# TODO

- [ ] Add /contact route
- [ ] Message form
  - [ ] Name, email fields
  - [ ] Markdown message editor
  - [ ] Email confirmation, that the message has been received (noreply@midka.dev) 
- [ ] GPG Keys
  - [ ] me@midka.dev
  - [ ] support@midka.dev
